### PR TITLE
specify Encoding UTF8 so characters like "ě" and "ř' show correctly

### PR DESCRIPTION
**Pull request by Sjors-Boom**
Pull request for issue #15

### CODE REVIEW

**Comment by mmajcica** [comment]
@Sjors-Boom  This was fast, thanks.

I'll deploy the new version on the marketplace this evening, I do not have the necessary to do it right away.

**Comment by Sjors-Boom** [comment]
Thanks!
We'll be looking forward for the update so we can incorporate this in our release pipeline!

**Comment by mmajcica** [comment]
@Sjors-Boom released in version 1.0.4

**Comment by mmajcica** [comment]
I'm glad to hear that!

Good luck and if you have time, please rate the extension in the marketplace!

**Pull request merged**
