### PR TITLE
Use reference instead of name while setting DataSet and DataSource item reference with SetItemReferences

### LINKED ISSUE #69: DataSet name is still used instead of SharedDataSetReference when linking
Hi, 

First thanks for that useful extension! It provides all I need for efficient continuous integration with SSRS.

This issue is closely linked to [](https://github.com/mmajcica/DeploySsrs/issues/28#issue-427635501). Correction would improve that shareddatasetreference matching.

I've been  investigating why, having all datasets and data sources in the config file, I still have warnings like this :

2021-03-10T15:38:31.4605597Z ##[warning]The reference for dataset ListCountry can not be found.

The strange thing is that the dataset are most of the time correctly linked! 
Also, I've also noticed that some datasets where wrongly assigned. 
After investigation, it seems that it is due to the fact that I have some datasets in the config file with the same name as the datasetname (and not the SharedDataSetReference name). 

Datasets are assigned twice to the reports in the PS New-SsrsReport function, first time in this code : 

`@($Datasets | Where-Object { $_.Name -eq $node.ParentNode.Name }) | ForEach-Object { $node.SharedDataSetReference = $_.Path }
`
Second time by updating the references in this code :

```
                foreach($node in $nodes)
                {
                    $ds = $DataSets | Where-Object { $_.Name -eq $node.ParentNode.Name } | Select-Object -First 1

                    if ($ds)
                    {
                        $Reference = New-Object -TypeName SSRS.ReportingService2010.ItemReference
                        $Reference.Reference = $ds.Path
                        $Reference.Name = $ds.Name
                
                        $References += $Reference
                    }
                    else
                    {
                        Write-Warning "The reference for dataset $($node.ParentNode.Name) can not be found."
                    }
                }

                if ($References)
                {
                    $Proxy.SetItemReferences($report.Path, $References)
                }
```

This means that if I have a in the config file named X and in the report, a dataset name Y while the shareddatasetreference name is X, it will be correctly assigned by first lines of code while the second will generate a warning. Which is not correct and very confusing.

In another case, I could have a dataset X, dataset name X in the report and shareddatasetreference name Y, then the dataset X will be assigned, finaly, because first line will not match and second will work. Maybe I have both X and Y defined in my config file... then comes wrong assignment.

All that is pretty confusing, an I quess the best solution would be to use shareddatasetreference name in both methods.

### PR DESCRIPTION
**Pull request by GregoryOtt**
fixes #69 and complete #52 

I've added the @muad81's solution for references already containing a path.

### CODE REVIEW

**Comment by mmajcica** [comment]
This looks good. I have no possibility to test it but it makes sense. Today I'll try to see if I can figure out why my deployment pipeline is not working and eventually publish a new version.

**Comment by GregoryOtt** [comment]
@mmajcica may I help you?
The problem is due to the version set by the Build. You should change the [versionning pattern](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml) to avoid the 090 part that is not valid for an extension.

**Comment by mmajcica** [comment]
Sorry, I have not found the time in the last 3 days. Different priorities. I'll try to get it done today, if unable, I will give you the sufficient rights to bring this to the marketplace.

**Comment by mmajcica** [comment]
@GregoryOtt finally done, sorry for poor reaction times.

**Pull request merged**
